replicaCount: 1

image:
  repository: ghcr.io/dclawstack/dclaw-warehouse
  pullPolicy: IfNotPresent
  tag: ""

service:
  type: ClusterIP
  port: 8138

ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - host: warehouse.dclawstack.io
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

postgresql:
  enabled: true
  auth:
    username: postgres
    password: postgres
    database: dclaw_warehouse
  primary:
    persistence:
      enabled: true
      size: 10Gi

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}
podSecurityContext: {}
securityContext: {}
nodeSelector: {}
tolerations: []
affinity: {}
